import React, { useState, useMemo, useEffect, useRef, memo, useContext, createContext } from 'react';
import { Eraser, Activity, ArrowUp, ArrowDown, X, GripVertical } from 'lucide-react';
import { clsx } from 'clsx';
import { twMerge } from 'tailwind-merge';
import { motion, AnimatePresence, Reorder, useDragControls } from 'framer-motion';
import stocksData from '../stocks_nsecm.json';

function cn(...inputs) {
    return twMerge(clsx(inputs));
}

// ---------- Default stock list (no indices any more) ----------
// Each entry MUST be present in src/stocks_nsecm.json (generated by
// `python scripts/parse_stocks.py`).
const DEFAULT_STOCK_SYMBOLS = [
    'RELIANCE',
    'HDFCBANK',
    'ICICIBANK',
    'BHARTIARTL',
    'INFY',
    'SBIN',
];

// Approximate market caps (₹ Lakh Crore) for the default stocks. Used to sort
// columns ascending. Anything missing falls back to Infinity (sorted last).
const MARKET_CAP = {
    RELIANCE: 17.0,
    HDFCBANK: 12.5,
    BHARTIARTL: 10.0,
    ICICIBANK: 9.5,
    INFY: 7.5,
    SBIN: 7.0,
};

// Build a stock entry from a NSECM symbol. Returns null if symbol not found.
const buildStockFromSymbol = (sym) => {
    const row = stocksData.find(r => r.s === sym && (r.x === 'NSECM' || r.x === 'NSE'));
    if (!row) {
        console.warn('[VerticalLayout] symbol not found in stocks_nsecm.json:', sym);
        return null;
    }
    return {
        id: sym,
        symbol: sym,
        tkn: row.t,
        xchg: 'NSECM',
        desc: row.d || sym,
        kind: 'stock',
    };
};

// ---------- Volume / price field readers ----------
const VOLUME_KEYS = ['TTQ', 'ttq', 'TotalTradedQty', 'TotalTradedQuantity', 'Volume', 'V', 'vol', 'volume'];
const PRICE_KEYS = ['LTP', 'ltp', 'LastTradedPrice', 'Price', 'lp', 'iv'];

const readField = (packet, keys) => {
    if (!packet) return null;
    for (const k of keys) {
        if (packet[k] !== undefined && packet[k] !== null && packet[k] !== '') {
            const n = Number(packet[k]);
            if (!Number.isNaN(n)) return n;
        }
    }
    return null;
};

// Raw data granularity — every packet is bucketed at this resolution.
// Display aggregates upward (30s, 1m, 5m, …) from this base.
const RAW_BUCKET_MINUTES = 0.25; // 15 seconds

// Round a timestamp DOWN to the start of its N-minute bucket.
// For buckets >= 1 minute: format as HH:MM (e.g. 14:23, bucket=5 → "14:20").
// For sub-minute buckets: format as HH:MM:SS (e.g. 14:23:37, bucket=0.25 → "14:23:30").
const fmtBucket = (ts, bucketMinutes = 1) => {
    const d = new Date(ts);
    const hh = d.getHours().toString().padStart(2, '0');
    if (bucketMinutes >= 1) {
        const bucketed = Math.floor(d.getMinutes() / bucketMinutes) * bucketMinutes;
        const mm = bucketed.toString().padStart(2, '0');
        return `${hh}:${mm}`;
    }
    // Sub-minute: bucket by seconds
    const bucketSec = Math.round(bucketMinutes * 60);
    const totalSec = d.getMinutes() * 60 + d.getSeconds();
    const bucketed = Math.floor(totalSec / bucketSec) * bucketSec;
    const mm = Math.floor(bucketed / 60).toString().padStart(2, '0');
    const ss = (bucketed % 60).toString().padStart(2, '0');
    return `${hh}:${mm}:${ss}`;
};

// Re-aggregate existing per-stock history into a new bucket size. Preserves
// every data point (no wipe). For smaller→larger this merges adjacent small
// buckets into a new large one; for larger→smaller, each old bucket maps to
// a single new-keyed row because we can't split volume we don't have.
//
// Each aggregated row keeps these invariants:
//   startCum = first row's startCum (the TTQ before the bucket began)
//   cumVol   = last row's cumVol   (the TTQ at the end of the bucket)
//   delta    = cumVol - startCum   (volume traded across the whole bucket)
//
// So vol - startCum = delta stays consistent, and future packet updates
// within the same new bucket work correctly without further fixups.
const reBucketHistories = (histories, newBucketMinutes) => {
    const result = {};
    for (const [stockId, rows] of Object.entries(histories || {})) {
        if (!Array.isArray(rows) || rows.length === 0) {
            result[stockId] = [];
            continue;
        }

        // Group existing rows by their NEW bucket key computed from timestamp
        const grouped = new Map();
        for (const row of rows) {
            const ts = row.timestamp || Date.now();
            const key = fmtBucket(ts, newBucketMinutes);
            if (!grouped.has(key)) grouped.set(key, []);
            grouped.get(key).push(row);
        }

        const aggregated = [];
        for (const [key, group] of grouped) {
            group.sort((a, b) => (a.timestamp || 0) - (b.timestamp || 0));
            const first = group[0];
            const last  = group[group.length - 1];

            const startCum = first.startCum ?? ((first.cumVol || 0) - (first.delta || 0));
            const cumVol   = last.cumVol ?? startCum;
            const delta    = Math.max(0, cumVol - startCum);

            aggregated.push({
                minute: key,
                cumVol,
                delta,
                timestamp: last.timestamp,
                startCum,
                priceOpen: first.priceOpen,
                priceClose: last.priceClose,
            });
        }

        aggregated.sort((a, b) => (a.timestamp || 0) - (b.timestamp || 0));
        // cap row count (1500 ≈ 6+ hours at 15s raw granularity)
        result[stockId] = aggregated.length > 1500 ? aggregated.slice(-1500) : aggregated;
    }
    return result;
};

// Volume display unit. 'auto' picks K/L/Cr based on magnitude. K/L/Cr force.
const VolumeUnitContext = createContext('auto');

const fmtVol = (n, forceUnit = 'auto') => {
    if (n === null || n === undefined || Number.isNaN(n)) return '—';
    if (forceUnit === 'Cr') return (n / 1e7).toFixed(2) + ' Cr';
    if (forceUnit === 'L') return (n / 1e5).toFixed(2) + ' L';
    if (forceUnit === 'K') return (n / 1e3).toFixed(2) + ' K';
    if (Math.abs(n) >= 1e7) return (n / 1e7).toFixed(2) + ' Cr';
    if (Math.abs(n) >= 1e5) return (n / 1e5).toFixed(2) + ' L';
    if (Math.abs(n) >= 1e3) return (n / 1e3).toFixed(2) + ' K';
    return n.toLocaleString();
};

const splitVol = (n, forceUnit = 'auto') => {
    if (n === null || n === undefined || Number.isNaN(n)) return { value: '—', unit: '' };
    if (forceUnit === 'Cr') return { value: (n / 1e7).toFixed(2), unit: 'Cr' };
    if (forceUnit === 'L') return { value: (n / 1e5).toFixed(2), unit: 'L' };
    if (forceUnit === 'K') return { value: (n / 1e3).toFixed(2), unit: 'K' };
    if (Math.abs(n) >= 1e7) return { value: (n / 1e7).toFixed(2), unit: 'Cr' };
    if (Math.abs(n) >= 1e5) return { value: (n / 1e5).toFixed(2), unit: 'L' };
    if (Math.abs(n) >= 1e3) return { value: (n / 1e3).toFixed(2), unit: 'K' };
    return { value: Math.round(n).toLocaleString(), unit: '' };
};

// Ultra-compact volume formatter for chart Y-axis labels.
// 1 decimal max, NO space before unit, drops trailing ".0".
// e.g. 6736000 -> "67.4L", 5052000 -> "50.5L", 100 -> "100"
const fmtAxisVol = (n, forceUnit = 'auto') => {
    if (n === null || n === undefined || Number.isNaN(n)) return '—';
    let v, u;
    if (forceUnit === 'Cr') { v = n / 1e7; u = 'Cr'; }
    else if (forceUnit === 'L') { v = n / 1e5; u = 'L'; }
    else if (forceUnit === 'K') { v = n / 1e3; u = 'K'; }
    else if (Math.abs(n) >= 1e7) { v = n / 1e7; u = 'Cr'; }
    else if (Math.abs(n) >= 1e5) { v = n / 1e5; u = 'L'; }
    else if (Math.abs(n) >= 1e3) { v = n / 1e3; u = 'K'; }
    else return Math.round(n).toString();
    return v.toFixed(1).replace(/\.0$/, '') + u;
};

// Renders a number + its unit in two slots so number digits always line up.
const VolCell = ({ n, className, unitClassName }) => {
    const forceUnit = useContext(VolumeUnitContext);
    const { value, unit } = splitVol(n, forceUnit);
    return (
        <span className={cn("inline-flex items-baseline justify-end gap-1 font-mono tabular-nums whitespace-nowrap", className)}>
            <span className="text-right">{value}</span>
            <span className={cn("inline-block w-[26px] text-left text-[15px] font-black opacity-90", unitClassName)}>{unit}</span>
        </span>
    );
};

// ---------- Helpers shared by row + bar ----------
const candleOf = (row) =>
    row.priceClose != null && row.priceOpen != null
        ? (row.priceClose > row.priceOpen ? 'up'
            : row.priceClose < row.priceOpen ? 'down'
                : 'flat')
        : 'flat';

const ROW_HEIGHT = 26; // px — used to align value rows

// ---------- Single VALUE row ----------
// MIN | arrow + Δ VOL
const VALUES_GRID = "grid grid-cols-[46px_1fr] items-center gap-1 px-2";

const MinuteRow = memo(React.forwardRef(({ row, isLatest, prevDelta, consensus, isPinned }, ref) => {
    const isRecent = row.timestamp ? (Date.now() - row.timestamp <= 60000) : false;
    const candle = candleOf(row);

    // Volume trend arrow (delta vs previous minute's delta) — DISABLED for now.
    // Kept the prevDelta prop on the signature so callers don't need to change
    // when this is re-enabled. To restore, uncomment the `volTrend` compute
    // and the ArrowUp/ArrowDown block inside the return below.
    // const volTrend = prevDelta == null
    //     ? null
    //     : (row.delta > prevDelta ? 'up' : row.delta < prevDelta ? 'down' : 'flat');

    const valueColorCls =
        candle === 'up' ? "text-emerald-300"
            : candle === 'down' ? "text-red-300"
                : "text-white/70";

    return (
        <motion.div
            ref={ref}
            layout
            initial={{ opacity: 0, x: -6 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.18 }}
            style={{ height: ROW_HEIGHT }}
            className={cn(
                VALUES_GRID,
                "border-b last:border-0 transition-all overflow-hidden",
                // ----- consensus highlight wins over everything else -----
                consensus === 'up'
                    ? "bg-emerald-500/25 border-emerald-400/60 shadow-[0_0_12px_rgba(52,211,153,0.35)]"
                    : consensus === 'down'
                        ? "bg-red-500/25 border-red-400/60 shadow-[0_0_12px_rgba(248,113,113,0.35)]"
                        : isLatest
                            ? "bg-amber-500/15 border-amber-500/40 shadow-[0_0_10px_rgba(251,191,36,0.2)]"
                            : isRecent
                                ? "bg-white/[0.04] border-white/10"
                                : "border-white/5 opacity-80",
                // pinned rows get a left-edge accent so the user knows they
                // were "rescued" from the regular flow
                isPinned && "border-l-2",
                isPinned && consensus === 'up' && "border-l-emerald-400",
                isPinned && consensus === 'down' && "border-l-red-400",
            )}
        >
            {/* MIN */}
            <span className={cn(
                "font-mono font-black whitespace-nowrap text-left tabular-nums tracking-tight text-[13px]",
                consensus === 'up'   ? "text-emerald-200" :
                consensus === 'down' ? "text-red-200" :
                isLatest             ? "text-amber-200" :
                isRecent             ? "text-blue-200" :
                                       "text-blue-500"
            )}>
                {row.minute}
            </span>

            {/* Δ VOL — volume-trend arrow disabled (re-enable via commented block above) */}
            <div className="flex items-center justify-end gap-0.5">
                <VolCell
                    n={row.delta}
                    className={cn(
                        "tracking-tight font-black text-[15px]",
                        consensus === 'up'   ? "text-emerald-200" :
                        consensus === 'down' ? "text-red-200" :
                                               valueColorCls
                    )}
                    unitClassName="text-[12px] w-[18px]"
                />
            </div>
        </motion.div>
    );
}), (prev, next) =>
    prev.row.minute === next.row.minute &&
    prev.row.delta === next.row.delta &&
    prev.row.priceOpen === next.row.priceOpen &&
    prev.row.priceClose === next.row.priceClose &&
    prev.isLatest === next.isLatest &&
    prev.prevDelta === next.prevDelta &&
    prev.consensus === next.consensus &&
    prev.isPinned === next.isPinned
);

// ---------- VolumeChart ----------
// Bottom 30% of each column. Real-time horizontally-scrollable bar chart of
// per-minute Δ-volume for ONE stock. Y-axis: scaled to max in window.
// X-axis: minute labels (sparse). Auto-scrolls right when new bars arrive,
// but user can scroll back to inspect earlier bars.
const VolumeChart = memo(({ history }) => {
    const forceUnit = useContext(VolumeUnitContext);
    const data = history;

    // Layout
    const BAR_W = 8;
    const GAP = 2;
    const PAD_L = 28;     // y-axis label gutter (compact axis labels need less)
    const PAD_R = 6;
    const PAD_T = 6;
    const PAD_B = 16;     // x-axis label strip
    const LEFT_GAP = 10;  // breathing room before the first bar

    const scrollerRef = useRef(null);
    const [chartH, setChartH] = useState(140);
    const [hovered, setHovered] = useState(null); // { row, x, y } — hover-driven

    // Track container height
    useEffect(() => {
        if (!scrollerRef.current) return;
        const el = scrollerRef.current;
        const ro = new ResizeObserver((entries) => {
            for (const e of entries) setChartH(e.contentRect.height);
        });
        ro.observe(el);
        return () => ro.disconnect();
    }, []);

    // Auto-scroll to right whenever a new bar appears (unless user scrolled away)
    const lastLen = useRef(0);
    useEffect(() => {
        if (!scrollerRef.current) return;
        const wasAtRight = scrollerRef.current.scrollLeft + scrollerRef.current.clientWidth
            >= scrollerRef.current.scrollWidth - 20;
        if (data.length !== lastLen.current && (wasAtRight || lastLen.current === 0)) {
            requestAnimationFrame(() => {
                if (scrollerRef.current) {
                    scrollerRef.current.scrollLeft = scrollerRef.current.scrollWidth;
                }
            });
        }
        lastLen.current = data.length;
    }, [data.length]);

    // Wheel-to-horizontal scroll inside the chart
    useEffect(() => {
        const el = scrollerRef.current;
        if (!el) return;
        const onWheel = (e) => {
            if (e.deltaY !== 0 || e.deltaX !== 0) {
                e.preventDefault();
                e.stopPropagation();
                el.scrollLeft += (e.deltaY || 0) + (e.deltaX || 0);
            }
        };
        el.addEventListener('wheel', onWheel, { passive: false });
        return () => el.removeEventListener('wheel', onWheel);
    }, []);

    // Tooltip is hover-only — no document listener needed.

    const maxDelta = useMemo(() => {
        let m = 0;
        for (const r of data) if ((r.delta || 0) > m) m = r.delta;
        return m;
    }, [data]);

    const innerW = Math.max(1, data.length * (BAR_W + GAP));
    const innerH = Math.max(1, chartH - PAD_T - PAD_B);

    // Y-axis tick values: 0, 25%, 50%, 75%, 100%
    const yTicks = [1, 0.75, 0.5, 0.25, 0].map(p => ({
        p,
        value: maxDelta * p,
        y: PAD_T + (1 - p) * innerH,
    }));

    // Decide which bars get an x-axis label. Show every 6th bar AND the latest,
    // but suppress the "every 6th" label if it sits within 4 bars of the end
    // (so it never overlaps the latest label).
    const labelShouldShow = (i) => {
        if (i === data.length - 1) return true;            // always show latest
        if (i % 6 !== 0) return false;                     // sparse grid
        return (data.length - 1 - i) >= 4;                 // not too close to end
    };

    return (
        <div className="h-full w-full flex bg-black/30 border-t border-white/10 pl-2 relative">
            {/* Y-axis (fixed, doesn't scroll) */}
            <div
                className="relative flex-shrink-0 border-r border-white/10"
                style={{ width: PAD_L }}
            >
                {yTicks.map(t => (
                    <div
                        key={t.p}
                        className="absolute right-0.5 -translate-y-1/2 text-[10px] text-white/75 font-mono font-bold tabular-nums whitespace-nowrap"
                        style={{ top: t.y }}
                    >
                        {fmtAxisVol(t.value, forceUnit)}
                    </div>
                ))}
            </div>

            {/* Scrollable chart */}
            <div
                ref={scrollerRef}
                className="flex-1 overflow-x-auto overflow-y-hidden scrollbar-thin [&::-webkit-scrollbar]:h-1.5 [&::-webkit-scrollbar-thumb]:bg-white/25 relative"
            >
                <svg
                    width={innerW + LEFT_GAP + PAD_R}
                    height={chartH}
                    className="block"
                >
                    {/* Horizontal grid lines */}
                    {yTicks.map(t => (
                        <line
                            key={t.p}
                            x1={0}
                            x2={innerW + LEFT_GAP + PAD_R}
                            y1={t.y}
                            y2={t.y}
                            stroke="rgba(255,255,255,0.08)"
                            strokeWidth={1}
                        />
                    ))}

                    {/* Bars (offset by LEFT_GAP so they don't hug the y-axis) */}
                    {data.map((r, i) => {
                        const candle = candleOf(r);
                        const fill =
                            candle === 'up' ? '#34d399' :
                                candle === 'down' ? '#f87171' :
                                    'rgba(255,255,255,0.25)';
                        const ratio = maxDelta > 0 ? (r.delta || 0) / maxDelta : 0;
                        const h = Math.max(1, ratio * innerH);
                        const x = LEFT_GAP + i * (BAR_W + GAP);
                        const y = PAD_T + innerH - h;
                        const isLast = i === data.length - 1;
                        const isHovered = hovered?.row?.minute === r.minute;

                        return (
                            <g key={r.minute}>
                                {/* Hover hit-area: full-column-height invisible rect so the
                                  user doesn't have to land precisely on the bar */}
                                <rect
                                    x={x - 1}
                                    y={PAD_T}
                                    width={BAR_W + 2}
                                    height={innerH}
                                    fill="transparent"
                                    style={{ cursor: 'pointer' }}
                                    onMouseEnter={() => setHovered({ row: r, x: x + BAR_W / 2, y })}
                                    onMouseLeave={() => setHovered(null)}
                                />
                                <rect
                                    x={x}
                                    y={y}
                                    width={BAR_W}
                                    height={h}
                                    fill={fill}
                                    rx={1.5}
                                    opacity={isLast ? 1 : 0.9}
                                    style={{ pointerEvents: 'none' }}
                                />
                                {isHovered && (
                                    <rect
                                        x={x - 1}
                                        y={y - 1}
                                        width={BAR_W + 2}
                                        height={h + 2}
                                        fill="none"
                                        stroke="#fbbf24"
                                        strokeWidth={1.5}
                                        rx={2}
                                        style={{ pointerEvents: 'none' }}
                                    />
                                )}
                                {labelShouldShow(i) && (
                                    <text
                                        x={x + BAR_W / 2}
                                        y={chartH - 4}
                                        textAnchor="middle"
                                        fontSize="10"
                                        fontWeight="700"
                                        fill="rgba(255,255,255,0.85)"
                                        fontFamily="ui-monospace, monospace"
                                        style={{ pointerEvents: 'none' }}
                                    >
                                        {r.minute}
                                    </text>
                                )}
                            </g>
                        );
                    })}

                    {/* Empty state */}
                    {data.length === 0 && (
                        <text
                            x={20}
                            y={chartH / 2}
                            fontSize="11"
                            fill="rgba(255,255,255,0.25)"
                            fontFamily="ui-monospace, monospace"
                            fontStyle="italic"
                        >
                            no data yet
                        </text>
                    )}
                </svg>

                {/* Tooltip — appears on hover. Position is computed so it never
                    overlaps the bar or runs off the visible chart edges. */}
                {hovered && (() => {
                    const candle = candleOf(hovered.row);
                    const candleColor =
                        candle === 'up' ? 'text-emerald-300' :
                            candle === 'down' ? 'text-red-300' : 'text-white/60';

                    const TOOLTIP_W = 140;
                    const TOOLTIP_H = 78;

                    const scroller = scrollerRef.current;
                    const scrollLeft = scroller?.scrollLeft || 0;
                    const clientW = scroller?.clientWidth || 200;

                    // Bar's x in viewport coordinates (visible portion of the chart)
                    const barViewX = hovered.x - scrollLeft;

                    // Place tooltip to the LEFT of the bar if bar is in the right
                    // half of the visible area, otherwise to the RIGHT.
                    let left;
                    if (barViewX > clientW / 2) {
                        left = hovered.x - TOOLTIP_W - 8;
                    } else {
                        left = hovered.x + BAR_W + 8;
                    }
                    // Clamp horizontally to the visible viewport so the tooltip
                    // can never escape the chart edges.
                    left = Math.max(scrollLeft + 4, Math.min(scrollLeft + clientW - TOOLTIP_W - 4, left));

                    // Vertical: try above the bar; flip below if not enough room.
                    let top = hovered.y - TOOLTIP_H - 6;
                    if (top < 4) top = hovered.y + 12;
                    top = Math.max(4, Math.min(chartH - TOOLTIP_H - 4, top));

                    return (
                        <div
                            className="absolute z-40 bg-[#0f1115] border border-amber-400/60 rounded-lg shadow-2xl px-2 py-1.5 pointer-events-none"
                            style={{
                                left,
                                top,
                                width: TOOLTIP_W,
                            }}
                        >
                            <div className="text-[11px] font-black text-amber-300 font-mono tabular-nums leading-tight border-b border-white/10 pb-1 mb-1">
                                {hovered.row.minute}
                            </div>
                            <div className="flex items-center justify-between gap-2">
                                <span className="text-[9px] uppercase font-bold text-white/40">Δ Vol</span>
                                <span className={cn("text-[12px] font-black font-mono tabular-nums", candleColor)}>
                                    {fmtVol(hovered.row.delta, forceUnit)}
                                </span>
                            </div>
                            <div className="flex items-center justify-between gap-2">
                                <span className="text-[9px] uppercase font-bold text-white/40">Cum</span>
                                <span className="text-[12px] font-black text-violet-200 font-mono tabular-nums">
                                    {fmtVol(hovered.row.cumVol, forceUnit)}
                                </span>
                            </div>
                            {hovered.row.priceOpen != null && hovered.row.priceClose != null && (
                                <div className="flex items-center justify-between gap-2 mt-0.5 pt-0.5 border-t border-white/10">
                                    <span className="text-[9px] uppercase font-bold text-white/40">O/C</span>
                                    <span className={cn("text-[10px] font-black font-mono tabular-nums", candleColor)}>
                                        {Number(hovered.row.priceOpen).toFixed(2)}→{Number(hovered.row.priceClose).toFixed(2)}
                                    </span>
                                </div>
                            )}
                        </div>
                    );
                })()}
            </div>
        </div>
    );
}, (prev, next) => {
    if (prev.history.length !== next.history.length) return false;
    if (prev.history.length === 0) return true;
    const a = prev.history[prev.history.length - 1];
    const b = next.history[next.history.length - 1];
    return a.minute === b.minute &&
        a.delta === b.delta &&
        a.priceOpen === b.priceOpen &&
        a.priceClose === b.priceClose;
});

// Resize bounds (px). The user can drag the right edge of any column between
// these. ~5% bigger than the previous range.
const COL_MIN_W = 170;
const COL_MAX_W = 320;
const COL_DEFAULT_W = 190;

// Fixed pixel height for the per-column volume chart panel. Locked so every
// column's chart looks identical, regardless of column height.
const CHART_H = 150;

// Per-stock identifier color used in the LeftSidebar so each row's arrows
// are visually identifiable as belonging to a specific stock.
const STOCK_COLOR_PALETTE = [
    '#f87171', // red
    '#fbbf24', // amber
    '#34d399', // emerald
    '#22d3ee', // cyan
    '#818cf8', // indigo
    '#f472b6', // pink
    '#a3e635', // lime
    '#fb923c', // orange
    '#c084fc', // violet
    '#2dd4bf', // teal
];
const colorForStock = (idx) => STOCK_COLOR_PALETTE[idx % STOCK_COLOR_PALETTE.length];

// ---------- Slim left sidebar ----------
// Sticks to the left edge. Aggregates the LATEST candle direction across every
// tracked stock and shows:
//   - top: green ↑ count (stocks currently bullish, i.e. last bucket close > open)
//          followed by chips listing the actual stock symbols in that group
//   - bottom: red ↓ count (stocks currently bearish) + chips of their symbols
// This way the user sees both "how many stocks are being bought right now" AND
// exactly which ones at a glance.
const LeftSidebar = memo(({ stocks, histories, snapshots, width }) => {
    const forceUnit = useContext(VolumeUnitContext);
    const { upStocks, downStocks, neutralStocks } = useMemo(() => {
        const up = [], down = [], neutral = [];
        for (const stock of stocks) {
            const hist = histories[stock.id] || [];
            if (hist.length === 0) {
                neutral.push(stock);
                continue;
            }
            const latest = hist[hist.length - 1];
            const candle = candleOf(latest);
            if (candle === 'up') up.push(stock);
            else if (candle === 'down') down.push(stock);
            else neutral.push(stock);
        }
        return { upStocks: up, downStocks: down, neutralStocks: neutral };
    }, [stocks, histories]);

    return (
        <div
            style={{ width: width || 110 }}
            className="flex-shrink-0 bg-[#0a0a0e] border-r border-white/10 overflow-y-auto scrollbar-thin [&::-webkit-scrollbar]:w-1 flex flex-col"
        >
            {/* Sticky title */}
            <div className="px-1.5 py-2 border-b border-white/10 sticky top-0 bg-[#0a0a0e] z-10">
                <div className="text-[8px] font-black text-white/40 uppercase tracking-wider text-center">
                    Market Pulse
                </div>
            </div>

            {/* spacer */}
            <div className="h-3 flex-shrink-0" />

            {/* ----- BULLISH (positive volume) — FIXED HEIGHT ----- */}
            <div
                style={{ height: 150 }}
                className="flex-shrink-0 flex flex-col border-y border-emerald-500/20 bg-emerald-500/[0.04] overflow-hidden"
            >
                <div className="px-2 py-1.5 flex items-center justify-between border-b border-emerald-500/10 flex-shrink-0">
                    <div className="flex items-center gap-1">
                        <ArrowUp size={13} className="text-emerald-400" strokeWidth={3.5} />
                        <span className="text-[8px] font-black uppercase tracking-wider text-emerald-400/80">Up</span>
                    </div>
                    <span className="text-[16px] font-black text-emerald-300 font-mono tabular-nums leading-none">
                        {upStocks.length}
                    </span>
                </div>
                <div className="flex-1 min-h-0 overflow-y-auto scrollbar-thin [&::-webkit-scrollbar]:w-1 px-1 pt-1 pb-1.5 space-y-0.5">
                    {upStocks.length === 0 ? (
                        <div className="text-[9px] text-emerald-400/30 italic text-center py-1">none</div>
                    ) : (
                        upStocks.map(s => (
                            <div
                                key={s.id}
                                className="flex items-center gap-1 px-1.5 py-0.5 rounded bg-emerald-500/10 border border-emerald-500/20"
                                title={s.symbol}
                            >
                                <ArrowUp size={9} className="text-emerald-400 shrink-0" strokeWidth={3.5} />
                                <span className="text-[10px] font-black text-emerald-200 truncate flex-1">
                                    {s.symbol}
                                </span>
                            </div>
                        ))
                    )}
                </div>
            </div>

            {/* ----- BEARISH (negative volume) — FIXED HEIGHT ----- */}
            <div
                style={{ height: 150 }}
                className="flex-shrink-0 flex flex-col border-b border-red-500/20 bg-red-500/[0.04] overflow-hidden"
            >
                <div className="px-2 py-1.5 flex items-center justify-between border-b border-red-500/10 flex-shrink-0">
                    <div className="flex items-center gap-1">
                        <ArrowDown size={13} className="text-red-400" strokeWidth={3.5} />
                        <span className="text-[8px] font-black uppercase tracking-wider text-red-400/80">Down</span>
                    </div>
                    <span className="text-[16px] font-black text-red-300 font-mono tabular-nums leading-none">
                        {downStocks.length}
                    </span>
                </div>
                <div className="flex-1 min-h-0 overflow-y-auto scrollbar-thin [&::-webkit-scrollbar]:w-1 px-1 pt-1 pb-1.5 space-y-0.5">
                    {downStocks.length === 0 ? (
                        <div className="text-[9px] text-red-400/30 italic text-center py-1">none</div>
                    ) : (
                        downStocks.map(s => (
                            <div
                                key={s.id}
                                className="flex items-center gap-1 px-1.5 py-0.5 rounded bg-red-500/10 border border-red-500/20"
                                title={s.symbol}
                            >
                                <ArrowDown size={9} className="text-red-400 shrink-0" strokeWidth={3.5} />
                                <span className="text-[10px] font-black text-red-200 truncate flex-1">
                                    {s.symbol}
                                </span>
                            </div>
                        ))
                    )}
                </div>
            </div>

            {/* ----- NEUTRAL / NO-DATA — FIXED HEIGHT (always rendered) ----- */}
            <div
                style={{ height: 110 }}
                className="flex-shrink-0 flex flex-col border-b border-white/10 bg-white/[0.02] overflow-hidden"
            >
                <div className="px-2 py-1 flex items-center justify-between border-b border-white/5 flex-shrink-0">
                    <span className="text-[8px] font-black uppercase tracking-wider text-white/40">Flat</span>
                    <span className="text-[12px] font-black text-white/30 font-mono tabular-nums">
                        {neutralStocks.length}
                    </span>
                </div>
                <div className="flex-1 min-h-0 overflow-y-auto scrollbar-thin [&::-webkit-scrollbar]:w-1 px-1 pt-1 pb-1.5 space-y-0.5">
                    {neutralStocks.length === 0 ? (
                        <div className="text-[9px] text-white/20 italic text-center py-1">none</div>
                    ) : (
                        neutralStocks.map(s => (
                            <div
                                key={s.id}
                                className="px-1.5 py-0.5 rounded bg-white/[0.04] border border-white/10"
                                title={s.symbol}
                            >
                                <span className="text-[10px] font-black text-white/40 truncate block">
                                    {s.symbol}
                                </span>
                            </div>
                        ))
                    )}
                </div>
            </div>

            {/* Cum Vol section removed — per user request. */}

            {stocks.length === 0 && (
                <div className="text-[9px] text-white/20 italic text-center py-4">
                    no stocks
                </div>
            )}
        </div>
    );
});

// Interval options for the per-column "Int. Vol" footer popover.
const INT_VOL_OPTIONS = [
    { value: 1, label: '1m' },
    { value: 5, label: '5m' },
    { value: 10, label: '10m' },
    { value: 15, label: '15m' },
    { value: 30, label: '30m' },
    { value: 60, label: '60m' },
];

// ---------- Totals column ----------
// A fixed column at the end of the list that aggregates EVERY stock's
// per-minute data into a single green/red view:
//   BOUGHT = sum of Δ-vol across stocks whose candle for that minute is up
//   SOLD   = sum of Δ-vol across stocks whose candle for that minute is down
// Does not participate in Reorder.Group, is not resizable, is not draggable.
const TotalsColumn = ({ stocks, histories }) => {
    const forceUnit = useContext(VolumeUnitContext);

    // Build a per-minute aggregate across all stocks. Key = minute label,
    // value = { bought, sold, timestamp }. We keep the latest timestamp seen
    // for sort + "isRecent" display logic.
    const rows = useMemo(() => {
        const byMinute = new Map();
        for (const stock of stocks) {
            const hist = histories[stock.id] || [];
            for (const row of hist) {
                const candle = candleOf(row);
                if (candle === 'flat') continue; // doesn't contribute to either bucket
                const existing = byMinute.get(row.minute) || {
                    minute: row.minute,
                    bought: 0,
                    sold: 0,
                    timestamp: 0,
                };
                if (candle === 'up')   existing.bought += row.delta || 0;
                if (candle === 'down') existing.sold   += row.delta || 0;
                if ((row.timestamp || 0) > existing.timestamp) existing.timestamp = row.timestamp || 0;
                byMinute.set(row.minute, existing);
            }
        }
        // Sort by timestamp ascending, then reverse so newest is on top in
        // the render (matches every other column).
        return [...byMinute.values()]
            .sort((a, b) => (a.timestamp || 0) - (b.timestamp || 0))
            .reverse()
            .slice(0, 250);
    }, [stocks, histories]);

    // Running totals across every minute we have
    const totalBought = useMemo(() => rows.reduce((s, r) => s + r.bought, 0), [rows]);
    const totalSold   = useMemo(() => rows.reduce((s, r) => s + r.sold,   0), [rows]);

    return (
        <div
            style={{ flex: '0 0 210px', maxWidth: 230, minWidth: 190 }}
            className="h-full flex flex-col bg-[#0f1115] border border-amber-500/30 rounded-lg shadow-xl relative"
        >
            {/* Header */}
            <div className="px-2 pt-2 pb-1.5 border-b border-white/10 space-y-1.5 bg-[#15171c]">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                        <Activity size={11} className="text-amber-400/80" />
                        <span className="text-[10px] font-bold text-white/50">AGGREGATE</span>
                    </div>
                    <span className="text-[8px] font-black text-amber-400/80 uppercase tracking-wider px-1 py-px rounded border border-amber-500/30 bg-amber-500/5">
                        TOTALS
                    </span>
                </div>
                <div className="flex items-center justify-between h-6 gap-1.5">
                    <div className="relative flex items-center h-full min-w-0 flex-1">
                        <span className="relative z-10 text-amber-300 text-[14px] font-black tracking-tight leading-none truncate">
                            TOTALS
                        </span>
                    </div>
                    <div className="flex items-center gap-1 bg-white/5 px-1.5 py-0.5 rounded border border-white/5 flex-shrink-0">
                        <span className="text-[9px] text-white/30 uppercase font-bold">Stocks</span>
                        <span className="text-[12px] font-bold text-yellow-500 font-mono tabular-nums">
                            {stocks.length}
                        </span>
                    </div>
                </div>
            </div>

            {/* Column header — MIN | BUY PRESSURE | SELL PRESSURE */}
            <div className="grid grid-cols-[46px_1fr_1fr] items-center gap-1 px-2 py-1 border-b border-white/5 bg-white/[0.02]">
                <span className="text-[10px] font-black text-blue-400/70 uppercase tracking-wider text-left">Min</span>
                <span className="text-[9px] font-black text-emerald-500 uppercase tracking-wider text-right pr-[20px] leading-tight">Buy Pressure</span>
                <span className="text-[9px] font-black text-red-500 uppercase tracking-wider text-right pr-[20px] leading-tight">Sell Pressure</span>
            </div>

            {/* Rows — one per unique minute across all stocks */}
            <div className="flex-1 min-h-0 overflow-y-auto scrollbar-thin [&::-webkit-scrollbar]:w-1 py-0.5">
                {rows.length === 0 ? (
                    <div className="text-[10px] text-white/20 text-center py-3 italic">
                        Waiting for data…
                    </div>
                ) : (
                    rows.map((r, idx) => {
                        const isRecent = r.timestamp ? (Date.now() - r.timestamp <= 60000) : false;
                        const isLatest = idx === 0;
                        return (
                            <div
                                key={r.minute}
                                style={{ height: ROW_HEIGHT }}
                                className={cn(
                                    "grid grid-cols-[46px_1fr_1fr] items-center gap-1 px-2 border-b last:border-0 transition-all overflow-hidden",
                                    isLatest
                                        ? "bg-amber-500/15 border-amber-500/40 shadow-[0_0_10px_rgba(251,191,36,0.2)]"
                                        : isRecent
                                            ? "bg-white/[0.04] border-white/10"
                                            : "border-white/5 opacity-80"
                                )}
                            >
                                <span className={cn(
                                    "font-mono font-black whitespace-nowrap text-left tabular-nums tracking-tight text-[13px]",
                                    isLatest ? "text-amber-200" : isRecent ? "text-blue-200" : "text-blue-500"
                                )}>
                                    {r.minute}
                                </span>
                                <VolCell
                                    n={r.bought}
                                    className={cn(
                                        "tracking-tight font-black text-[14px]",
                                        r.bought > 0 ? "text-emerald-300" : "text-white/20"
                                    )}
                                    unitClassName="text-[11px] w-[18px]"
                                />
                                <VolCell
                                    n={r.sold}
                                    className={cn(
                                        "tracking-tight font-black text-[14px]",
                                        r.sold > 0 ? "text-red-300" : "text-white/20"
                                    )}
                                    unitClassName="text-[11px] w-[18px]"
                                />
                            </div>
                        );
                    })
                )}
            </div>

            {/* Footer — running totals across the whole visible window */}
            <div className="px-2 py-1 border-t border-white/10 bg-white/[0.02] grid grid-cols-2 gap-1">
                <div className="grid grid-cols-[auto_1fr] items-center gap-1">
                    <span className="text-[9px] font-bold text-white/30 uppercase">Σ Buy</span>
                    <VolCell
                        n={totalBought}
                        className={cn(
                            "font-black text-[12px] tracking-tight justify-end",
                            totalBought > 0 ? "text-emerald-300" : "text-white/20"
                        )}
                        unitClassName="text-[10px] w-[18px]"
                    />
                </div>
                <div className="grid grid-cols-[auto_1fr] items-center gap-1">
                    <span className="text-[9px] font-bold text-white/30 uppercase">Σ Sell</span>
                    <VolCell
                        n={totalSold}
                        className={cn(
                            "font-black text-[12px] tracking-tight justify-end",
                            totalSold > 0 ? "text-red-300" : "text-white/20"
                        )}
                        unitClassName="text-[10px] w-[18px]"
                    />
                </div>
            </div>
        </div>
    );
};

// ---------- Net aggregate column ----------
// Sits after TotalsColumn. For each minute across all tracked stocks:
//   TOTAL    = buy-pressure + sell-pressure (the absolute activity)
//   5m AVG   = rolling mean of the last 5 rows' totals
// Rendered in yellow with the rolling avg in brackets inline.
const NetColumn = ({ stocks, histories }) => {
    const forceUnit = useContext(VolumeUnitContext);

    // Reuse the same per-minute aggregation logic as TotalsColumn. Each row
    // has .total (buy + sell) and the rolling average is computed as a mean
    // of the last 5 rows' totals (including the row itself).
    const rows = useMemo(() => {
        const byMinute = new Map();
        for (const stock of stocks) {
            const hist = histories[stock.id] || [];
            for (const row of hist) {
                const candle = candleOf(row);
                if (candle === 'flat') continue;
                const existing = byMinute.get(row.minute) || {
                    minute: row.minute,
                    total: 0,
                    timestamp: 0,
                };
                existing.total += row.delta || 0;
                if ((row.timestamp || 0) > existing.timestamp) existing.timestamp = row.timestamp || 0;
                byMinute.set(row.minute, existing);
            }
        }
        // Chronological ascending so the rolling window sees older rows first
        const chron = [...byMinute.values()]
            .sort((a, b) => (a.timestamp || 0) - (b.timestamp || 0));

        // Compute rolling 5-minute average of `total` for each row
        for (let i = 0; i < chron.length; i++) {
            const start = Math.max(0, i - 4);
            let sum = 0, cnt = 0;
            for (let j = start; j <= i; j++) {
                sum += chron[j].total;
                cnt++;
            }
            chron[i].rollingAvg5 = cnt > 0 ? sum / cnt : 0;
        }
        // Reverse so newest is on top (matches every other column)
        return chron.reverse().slice(0, 250);
    }, [stocks, histories]);

    const totalSum = useMemo(() => rows.reduce((s, r) => s + r.total, 0), [rows]);

    return (
        <div
            style={{ flex: '0 0 230px', maxWidth: 250, minWidth: 210 }}
            className="h-full flex flex-col bg-[#0f1115] border border-yellow-500/30 rounded-lg shadow-xl relative"
        >
            {/* Header */}
            <div className="px-2 pt-2 pb-1.5 border-b border-white/10 space-y-1.5 bg-[#15171c]">
                <div className="flex items-center justify-between">
                    <div className="flex items-center gap-1.5">
                        <Activity size={11} className="text-yellow-400/80" />
                        <span className="text-[10px] font-bold text-white/50">NET</span>
                    </div>
                    <span className="text-[8px] font-black text-yellow-400/80 uppercase tracking-wider px-1 py-px rounded border border-yellow-500/30 bg-yellow-500/5">
                        TOTAL + AVG
                    </span>
                </div>
                <div className="flex items-center justify-between h-6 gap-1.5">
                    <div className="relative flex items-center h-full min-w-0 flex-1">
                        <span className="relative z-10 text-yellow-300 text-[14px] font-black tracking-tight leading-none truncate">
                            NET VOL
                        </span>
                    </div>
                    <div className="flex items-center gap-1 bg-white/5 px-1.5 py-0.5 rounded border border-white/5 flex-shrink-0">
                        <span className="text-[9px] text-white/30 uppercase font-bold">5m Avg</span>
                    </div>
                </div>
            </div>

            {/* Column header — MIN | TOTAL + (5m AVG) */}
            <div className="grid grid-cols-[46px_1fr] items-center gap-1 px-2 py-1 border-b border-white/5 bg-white/[0.02]">
                <span className="text-[10px] font-black text-blue-400/70 uppercase tracking-wider text-left">Min</span>
                <span className="text-[10px] font-black text-yellow-400/80 uppercase tracking-wider text-right pr-1">
                    Total <span className="text-white/80">(5m Avg)</span>
                </span>
            </div>

            {/* Rows */}
            <div className="flex-1 min-h-0 overflow-y-auto scrollbar-thin [&::-webkit-scrollbar]:w-1 py-0.5">
                {rows.length === 0 ? (
                    <div className="text-[10px] text-white/20 text-center py-3 italic">
                        Waiting for data…
                    </div>
                ) : (
                    rows.map((r, idx) => {
                        const isRecent = r.timestamp ? (Date.now() - r.timestamp <= 60000) : false;
                        const isLatest = idx === 0;
                        return (
                            <div
                                key={r.minute}
                                style={{ height: ROW_HEIGHT }}
                                className={cn(
                                    "grid grid-cols-[46px_1fr] items-center gap-1 px-2 border-b last:border-0 transition-all overflow-hidden",
                                    isLatest
                                        ? "bg-amber-500/15 border-amber-500/40 shadow-[0_0_10px_rgba(251,191,36,0.2)]"
                                        : isRecent
                                            ? "bg-white/[0.04] border-white/10"
                                            : "border-white/5 opacity-80"
                                )}
                            >
                                <span className={cn(
                                    "font-mono font-black whitespace-nowrap text-left tabular-nums tracking-tight text-[13px]",
                                    isLatest ? "text-amber-200" : isRecent ? "text-blue-200" : "text-blue-500"
                                )}>
                                    {r.minute}
                                </span>
                                <div className="flex items-baseline justify-end gap-1.5">
                                    <VolCell
                                        n={r.total}
                                        className={cn(
                                            "tracking-tight font-black text-[14px]",
                                            r.total > 0 ? "text-yellow-300" : "text-white/20"
                                        )}
                                        unitClassName="text-[11px] w-[18px] text-yellow-400/70"
                                    />
                                    <span className="text-[12px] font-mono font-black text-white tabular-nums whitespace-nowrap">
                                        ({fmtVol(r.rollingAvg5, forceUnit)})
                                    </span>
                                </div>
                            </div>
                        );
                    })
                )}
            </div>

            {/* Footer — running grand total */}
            <div className="px-2 py-1 border-t border-white/10 bg-white/[0.02] grid grid-cols-[auto_1fr] items-center gap-1">
                <span className="text-[9px] font-bold text-white/30 uppercase">Σ Net</span>
                <VolCell
                    n={totalSum}
                    className={cn(
                        "font-black text-[12px] tracking-tight justify-end",
                        totalSum > 0 ? "text-yellow-300" : "text-white/20"
                    )}
                    unitClassName="text-[10px] w-[18px] text-yellow-400/70"
                />
            </div>
        </div>
    );
};

// ---------- One column for one stock ----------
// Wrapped as a Reorder.Item so the parent <Reorder.Group> can shuffle the
// columns horizontally. Drag handle is the GripVertical icon in the header.
// A right-edge handle resizes the column between COL_MIN_W and COL_MAX_W.
const StockColumn = ({
    stock, history, ltp, cumVolume,
    onClear, onRemove, isExtra,
    width, onResize,
    bucketSize,
    intVolMinutes, onChangeIntVol,
    consensusByMinute = {},
}) => {
    const forceUnit = useContext(VolumeUnitContext);
    const visible = useMemo(() => history.slice(-250), [history]);
    const reversed = useMemo(() => [...visible].reverse(), [visible]);
    const dragControls = useDragControls();
    const [intOpen, setIntOpen] = useState(false);
    const popRef = useRef(null);

    // Track the values area's actual rendered height so we can compute how
    // many rows fit and decide which consensus rows need pinning at the bottom.
    const valuesAreaRef = useRef(null);
    const [valuesAreaH, setValuesAreaH] = useState(400);
    useEffect(() => {
        const el = valuesAreaRef.current;
        if (!el) return;
        const ro = new ResizeObserver(([entry]) => {
            setValuesAreaH(entry.contentRect.height);
        });
        ro.observe(el);
        return () => ro.disconnect();
    }, []);

    // Reserve a small footer slice for the pinned consensus area.
    const PINNED_RESERVE = 4;     // up to 4 pinned rows
    const totalSlots = Math.max(1, Math.floor(valuesAreaH / ROW_HEIGHT));

    // Walk all rows newest-first. Anything that falls beyond the regular
    // visible window AND is consensus gets pinned at the bottom (capped to
    // PINNED_RESERVE so the pinned area stays bounded).
    const { regularRows, pinnedRows } = useMemo(() => {
        // Reserve the pinned slice if we have any consensus rows beyond the
        // visible window — otherwise give all the slots back to the regular
        // flow so we don't waste space.
        const candidatePinned = [];
        for (let i = 0; i < reversed.length; i++) {
            const c = consensusByMinute[reversed[i].minute];
            if ((c === 'up' || c === 'down') && i >= totalSlots - PINNED_RESERVE) {
                candidatePinned.push(reversed[i]);
            }
        }
        const usePinned = candidatePinned.slice(0, PINNED_RESERVE);
        const regularSlots = usePinned.length > 0
            ? Math.max(1, totalSlots - usePinned.length)
            : totalSlots;
        const regular = reversed.slice(0, regularSlots);
        // Make sure rows already shown in the regular section don't repeat in
        // the pinned section.
        const regularMinutes = new Set(regular.map(r => r.minute));
        const pinned = usePinned.filter(r => !regularMinutes.has(r.minute));
        return { regularRows: regular, pinnedRows: pinned };
    }, [reversed, consensusByMinute, totalSlots]);

    // Sum of last K rows whose total time covers `intVolMinutes`. Each row
    // represents `bucketSize` minutes, so K = ceil(intVolMinutes / bucketSize),
    // capped to history length.
    const intVolValue = useMemo(() => {
        const k = Math.max(1, Math.ceil((intVolMinutes || 1) / Math.max(1, bucketSize || 1)));
        const slice = visible.slice(-k);
        return slice.reduce((sum, r) => sum + (r.delta || 0), 0);
    }, [visible, intVolMinutes, bucketSize]);

    // Click-outside for the Int. Vol popover
    useEffect(() => {
        if (!intOpen) return;
        const onDoc = (e) => {
            if (popRef.current && !popRef.current.contains(e.target)) setIntOpen(false);
        };
        document.addEventListener('mousedown', onDoc);
        return () => document.removeEventListener('mousedown', onDoc);
    }, [intOpen]);

    // ---- Resize handle (right edge) ----
    const handleResizeStart = (e) => {
        e.stopPropagation();
        e.preventDefault();
        const startX = e.pageX;
        const startW = width;

        const onMove = (mv) => {
            const delta = mv.pageX - startX;
            const next = Math.min(COL_MAX_W, Math.max(COL_MIN_W, startW + delta));
            onResize(stock.id, next);
        };
        const onUp = () => {
            window.removeEventListener('pointermove', onMove);
            window.removeEventListener('pointerup', onUp);
            document.body.style.cursor = 'default';
            document.body.style.userSelect = '';
        };
        window.addEventListener('pointermove', onMove);
        window.addEventListener('pointerup', onUp);
        document.body.style.cursor = 'col-resize';
        document.body.style.userSelect = 'none';
    };

    return (
        <Reorder.Item
            value={stock.id}
            dragListener={false}
            dragControls={dragControls}
            whileDrag={{ scale: 1.02, zIndex: 50 }}
            style={{ flex: `0 0 ${width}px`, maxWidth: COL_MAX_W, minWidth: COL_MIN_W }}
            className="h-full flex flex-col bg-[#0f1115] border border-white/10 rounded-lg shadow-xl relative"
        >
            {/* ---- Right-edge resize handle ---- */}
            <div
                className="absolute right-0 top-0 w-1.5 h-full cursor-col-resize hover:bg-blue-500/30 z-50 transition-colors"
                onPointerDown={handleResizeStart}
                title="Drag to resize"
            />

            {/* Header */}
            <div className="px-2 pt-2 pb-1.5 border-b border-white/10 space-y-1.5 bg-[#15171c]">
                <div className="flex items-center justify-between">
                    <div
                        className="flex items-center gap-1.5 cursor-grab active:cursor-grabbing select-none"
                        onPointerDown={(e) => dragControls.start(e)}
                        title="Drag to reorder"
                    >
                        <GripVertical size={12} className="text-white/30 hover:text-white/60 transition-colors" />
                        <Activity size={11} className="text-emerald-400/60" />
                        <span className="text-[10px] font-bold text-white/50">{stock.xchg}</span>
                        {isExtra && (
                            <span className="text-[8px] font-black text-blue-400/80 uppercase tracking-wider px-1 py-px rounded border border-blue-500/30 bg-blue-500/5">
                                Custom
                            </span>
                        )}
                    </div>
                    <div className="flex items-center gap-0.5">
                        <button
                            onClick={() => onClear(stock.id)}
                            className="opacity-30 hover:opacity-100 transition-opacity p-0.5 hover:text-emerald-400 text-white/50"
                            title="Clear History"
                        >
                            <Eraser size={11} />
                        </button>
                        {isExtra && (
                            <button
                                onClick={() => onRemove(stock.id)}
                                className="opacity-30 hover:opacity-100 transition-opacity p-0.5 hover:text-red-400 text-white/50"
                                title="Remove Column"
                            >
                                <X size={11} />
                            </button>
                        )}
                    </div>
                </div>

                <div className="flex items-center justify-between h-6 gap-1.5">
                    <div className="relative flex items-center h-full min-w-0 flex-1">
                        <span className="relative z-10 text-cyan-400 text-[14px] font-black tracking-tight leading-none truncate">
                            {stock.symbol}
                        </span>
                    </div>
                    <div className="flex items-center gap-1 bg-white/5 px-1.5 py-0.5 rounded border border-white/5 flex-shrink-0">
                        <span className="text-[9px] text-white/30 uppercase font-bold">LTP</span>
                        <span className="text-[12px] font-bold text-yellow-500 font-mono tabular-nums">
                            {ltp !== null ? Number(ltp).toFixed(2) : '—'}
                        </span>
                    </div>
                </div>
            </div>

            {/* Column header bar — single row, MIN | Δ VOL */}
            <div className={cn(VALUES_GRID, "py-1 border-b border-white/5 bg-white/[0.02]")}>
                <span className="text-[10px] font-black text-blue-400/70 uppercase tracking-wider text-left">Min</span>
                <span className="text-[10px] font-black text-emerald-500 uppercase tracking-wider text-right pr-[20px]">Δ Vol</span>
            </div>

            {/* ----- Body: TOP values | BOTTOM chart -----
                  Chart is locked to a fixed pixel height (`CHART_H`) so every
                  column's chart panel matches exactly, regardless of column
                  height. The values list takes whatever's left. */}
            <div className="flex-1 flex flex-col min-h-0 overflow-hidden">
                {/* Values list — split into REGULAR (top) + PINNED CONSENSUS
                    (bottom). The pinned area only appears when consensus rows
                    exist beyond the visible window — they're guaranteed to
                    stay visible at the bottom of the column. */}
                <div
                    ref={valuesAreaRef}
                    className="flex-1 flex flex-col overflow-hidden py-0.5 min-h-0"
                >
                    {/* Regular rows (newest first, clipped after `regularRows.length`) */}
                    <div className="flex-1 overflow-hidden min-h-0">
                        <AnimatePresence initial={false} mode="popLayout">
                            {reversed.length === 0 ? (
                                <div className="text-[10px] text-white/20 text-center py-3 italic">
                                    Waiting for volume…
                                </div>
                            ) : (
                                regularRows.map((row, idx, arr) => {
                                    const prevDelta = arr[idx + 1]?.delta ?? null;
                                    return (
                                        <MinuteRow
                                            key={row.minute}
                                            row={row}
                                            isLatest={idx === 0}
                                            prevDelta={prevDelta}
                                            consensus={consensusByMinute[row.minute] || null}
                                        />
                                    );
                                })
                            )}
                        </AnimatePresence>
                    </div>

                    {/* Pinned consensus rows — anchored at the bottom of the
                        values area. These are consensus minutes that have
                        scrolled out of the regular window, "rescued" so they
                        stay visible. Older pinned rows sit at the bottom. */}
                    {pinnedRows.length > 0 && (
                        <div className="flex-shrink-0 border-t-2 border-amber-500/40 bg-black/40">
                            <AnimatePresence initial={false} mode="popLayout">
                                {pinnedRows.map((row) => (
                                    <MinuteRow
                                        key={`pinned-${row.minute}`}
                                        row={row}
                                        isLatest={false}
                                        prevDelta={null}
                                        consensus={consensusByMinute[row.minute] || null}
                                        isPinned
                                    />
                                ))}
                            </AnimatePresence>
                        </div>
                    )}
                </div>

                {/* Chart panel — FIXED HEIGHT identical for every column */}
                <div className="flex-shrink-0" style={{ height: CHART_H }}>
                    <VolumeChart history={visible} />
                </div>
            </div>

            {/* Footer: Cum Vol + clickable Int. Vol — fixed-grid layout so the
                  numbers/units across both halves all line up to consistent slots. */}
            <div className="px-2 py-1 border-t border-white/10 bg-white/[0.02] grid grid-cols-2 gap-1 relative">
                {/* CUM */}
                <div className="grid grid-cols-[auto_1fr] items-center gap-1">
                    <span className="text-[9px] font-bold text-white/30 uppercase">Cum</span>
                    <VolCell
                        n={cumVolume}
                        className={cn(
                            "font-black text-[12px] tracking-tight justify-end",
                            cumVolume > 0 ? "text-violet-300" : "text-white/20"
                        )}
                        unitClassName="text-[10px] w-[18px]"
                    />
                </div>

                {/* INT VOL — clickable */}
                <div className="relative" ref={popRef}>
                    <button
                        onClick={() => setIntOpen(o => !o)}
                        className="w-full grid grid-cols-[auto_auto_1fr] items-center gap-1 px-1 py-0.5 rounded border border-white/10 hover:border-emerald-500/40 hover:bg-emerald-500/5 transition-colors"
                        title="Click to choose interval"
                    >
                        <span className="text-[9px] font-bold text-white/40 uppercase">Int</span>
                        <span className="text-[9px] font-black text-emerald-400/80 font-mono tabular-nums">
                            {intVolMinutes}m
                        </span>
                        <VolCell
                            n={intVolValue}
                            className={cn(
                                "font-black text-[12px] tracking-tight justify-end",
                                intVolValue > 0 ? "text-emerald-300" : "text-white/20"
                            )}
                            unitClassName="text-[10px] w-[18px]"
                        />
                    </button>

                    {intOpen && (
                        <div className="absolute bottom-full right-0 mb-1 bg-[#0f1115] border border-white/15 rounded-lg shadow-2xl z-50 overflow-hidden min-w-[100px]">
                            <div className="text-[8px] font-black text-white/30 uppercase tracking-wider px-2 py-1 border-b border-white/10">
                                Interval
                            </div>
                            {INT_VOL_OPTIONS.map(o => (
                                <button
                                    key={o.value}
                                    onClick={() => {
                                        onChangeIntVol(stock.id, o.value);
                                        setIntOpen(false);
                                    }}
                                    className={cn(
                                        "w-full text-left px-2 py-1 text-[11px] font-mono font-bold transition-colors",
                                        o.value === intVolMinutes
                                            ? "bg-emerald-500/15 text-emerald-300"
                                            : "text-white/60 hover:bg-white/5 hover:text-white"
                                    )}
                                >
                                    {o.label}
                                </button>
                            ))}
                        </div>
                    )}
                </div>
            </div>
        </Reorder.Item>
    );
};

// ---------- Main Vertical Layout ----------
const VerticalLayout = ({
    visibleElements,
    isSidebarVisible,
    depthData,
    subscribe,
    extraStocks = [],          // [{ symbol }] from App.jsx dropdown
    onRemoveExtraStock,        // (symbol) => void
    bucketSize = 1,            // minutes per bucket (0.25=15s, 0.5=30s, 1, 5, 10, 15, 30)
    volumeUnit = 'auto',       // 'auto' | 'K' | 'L' | 'Cr'
    wsStatus = 'connected',    // current WebSocket status from useMarketData
    depthEvents,               // EventTarget that fires 'depth-packet' for every WS data packet
    monitorId = 0,             // which monitor / session this instance belongs to
    marketOpen = true,         // false during non-trading hours / weekends
}) => {
    const [timeTick, setTimeTick] = useState(0);

    // Suffix all localStorage keys with the monitor id so each monitor is a
    // fully isolated session.
    const keySuffix = `_m${monitorId}`;

    // ---------- Build the active stock list (defaults + extras), highest market cap first ----------
    const STOCK_LIST = useMemo(() => {
        const defaults = DEFAULT_STOCK_SYMBOLS
            .map(buildStockFromSymbol)
            .filter(Boolean)
            .sort((a, b) => (MARKET_CAP[b.symbol] ?? -Infinity) - (MARKET_CAP[a.symbol] ?? -Infinity));

        const extras = extraStocks
            .map(es => buildStockFromSymbol(es.symbol))
            .filter(Boolean)
            // de-dupe against defaults
            .filter(es => !defaults.some(d => d.symbol === es.symbol))
            .map(es => ({ ...es, isExtra: true }));

        return [...defaults, ...extras];
    }, [extraStocks]);

    // ---------- localStorage persistence ----------
    const STORAGE_KEY = `vl_state_v2${keySuffix}`; // bumped because schema added priceOpen/Close
    const todayKey = () => {
        const d = new Date();
        return `${d.getFullYear()}-${d.getMonth() + 1}-${d.getDate()}`;
    };

    const loadPersisted = () => {
        try {
            const raw = localStorage.getItem(STORAGE_KEY);
            if (!raw) return null;
            const parsed = JSON.parse(raw);
            // Discard if from a different day (TTQ resets each trading day).
            if (parsed?.day !== todayKey()) return null;
            // The current model stores raw 15-second data. Old persisted blobs
            // saved at a larger bucket size are aggregated and can't be split
            // back into 15s points, so we drop them on load.
            if (parsed?.bucketSize !== undefined && parsed.bucketSize !== RAW_BUCKET_MINUTES) return null;
            return parsed;
        } catch {
            return null;
        }
    };

    // Per-stock RAW 1-minute history (the source of truth).
    // The displayed/aggregated view is derived from this via
    // `displayedHistories = useMemo(...)` below.
    const [histories, setHistories] = useState(() => {
        const persisted = loadPersisted();
        const base = {};
        for (const s of STOCK_LIST) base[s.id] = [];
        if (persisted?.histories) {
            for (const s of STOCK_LIST) {
                const arr = persisted.histories[s.id];
                if (!Array.isArray(arr)) continue;
                // Scrub legacy zero-delta rows from before the cross-boundary
                // flush fix. Keep the most recent row (it can legitimately be
                // 0 while still being filled) and any row whose delta is > 0.
                if (arr.length === 0) {
                    base[s.id] = arr;
                    continue;
                }
                const lastIdx = arr.length - 1;
                base[s.id] = arr.filter((row, i) => i === lastIdx || (row.delta || 0) > 0);
            }
        }
        return base;
    });

    // Latest LTP / day volume per stock for header & footer
    const [snapshots, setSnapshots] = useState(() => {
        const persisted = loadPersisted();
        const base = {};
        for (const s of STOCK_LIST) base[s.id] = { ltp: null, vol: null };
        if (persisted?.snapshots) {
            for (const s of STOCK_LIST) {
                if (persisted.snapshots[s.id]) base[s.id] = persisted.snapshots[s.id];
            }
        }
        return base;
    });

    // ---------- Column ORDER (drag-and-drop) ----------
    const ORDER_KEY = `vl_column_order_v1${keySuffix}`;
    const [columnOrder, setColumnOrder] = useState(() => {
        try {
            const raw = localStorage.getItem(ORDER_KEY);
            if (raw) return JSON.parse(raw);
        } catch { }
        return STOCK_LIST.map(s => s.id);
    });
    useEffect(() => {
        try { localStorage.setItem(ORDER_KEY, JSON.stringify(columnOrder)); } catch { }
    }, [columnOrder]);

    // Sync column order with the active STOCK_LIST: drop removed stocks,
    // append newly added ones to the end.
    useEffect(() => {
        const ids = new Set(STOCK_LIST.map(s => s.id));
        setColumnOrder(prev => {
            const filtered = prev.filter(id => ids.has(id));
            const missing = STOCK_LIST.map(s => s.id).filter(id => !filtered.includes(id));
            const next = [...filtered, ...missing];
            // shallow equality check to avoid infinite re-renders
            if (next.length === prev.length && next.every((v, i) => v === prev[i])) return prev;
            return next;
        });
    }, [STOCK_LIST]);

    // Stocks rendered in the current draggable order
    const orderedStocks = useMemo(
        () => columnOrder.map(id => STOCK_LIST.find(s => s.id === id)).filter(Boolean),
        [columnOrder, STOCK_LIST]
    );

    // ---------- Displayed (aggregated) histories ----------
    // `histories` always holds raw 1-minute data. The displayed view that
    // every column / sidebar / totals component reads is derived from it via
    // reBucketHistories at the user's current bucket size. Switching the
    // timeframe just causes this memo to recompute — the underlying raw
    // data is never mutated, so going 1m → 5m → 1m correctly returns to
    // the original detail.
    const displayedHistories = useMemo(() => {
        if (bucketSize === RAW_BUCKET_MINUTES) return histories;
        return reBucketHistories(histories, bucketSize);
    }, [histories, bucketSize]);

    // ---------- Per-minute candle CONSENSUS across all tracked stocks ----------
    // For each minute, if EVERY tracked stock has a row for that minute AND
    // every one of those rows has the SAME candle direction (all green or all
    // red, no flat, no missing), the minute is marked as consensus. Computed
    // on the DISPLAYED histories so the minute keys line up with what the
    // columns are actually showing.
    const consensusByMinute = useMemo(() => {
        const map = {};
        if (orderedStocks.length === 0) return map;

        const perStock = orderedStocks.map(s => {
            const m = new Map();
            const hist = displayedHistories[s.id] || [];
            for (const row of hist) {
                m.set(row.minute, candleOf(row));
            }
            return m;
        });

        if (perStock.length === 0) return map;
        for (const [minute, c0] of perStock[0]) {
            if (c0 !== 'up' && c0 !== 'down') continue;
            let ok = true;
            for (let i = 1; i < perStock.length; i++) {
                const ci = perStock[i].get(minute);
                if (ci !== c0) { ok = false; break; }
            }
            if (ok) map[minute] = c0;
        }
        return map;
    }, [orderedStocks, displayedHistories]);

    // ---------- Column WIDTHS (resizable) ----------
    const WIDTHS_KEY = `vl_column_widths_v1${keySuffix}`;
    const [columnWidths, setColumnWidths] = useState(() => {
        try {
            const raw = localStorage.getItem(WIDTHS_KEY);
            if (raw) return JSON.parse(raw);
        } catch { }
        return {};
    });
    useEffect(() => {
        try { localStorage.setItem(WIDTHS_KEY, JSON.stringify(columnWidths)); } catch { }
    }, [columnWidths]);

    const handleResize = (stockId, width) => {
        setColumnWidths(prev => ({ ...prev, [stockId]: width }));
    };

    // ---------- Per-column Int. Vol interval ----------
    const INTVOL_KEY = `vl_int_vol_minutes_v1${keySuffix}`;
    const [intVolMinutes, setIntVolMinutes] = useState(() => {
        try {
            const raw = localStorage.getItem(INTVOL_KEY);
            if (raw) return JSON.parse(raw);
        } catch { }
        return {};
    });
    useEffect(() => {
        try { localStorage.setItem(INTVOL_KEY, JSON.stringify(intVolMinutes)); } catch { }
    }, [intVolMinutes]);

    const handleChangeIntVol = (stockId, mins) => {
        setIntVolMinutes(prev => ({ ...prev, [stockId]: mins }));
    };

    // ---------- LeftSidebar resizable width ----------
    const SIDEBAR_MIN = 90;
    const SIDEBAR_MAX = 220;
    const SIDEBAR_DEFAULT = 120;
    const SIDEBAR_KEY = `vl_sidebar_width_v1${keySuffix}`;
    const [sidebarWidth, setSidebarWidth] = useState(() => {
        try {
            const raw = localStorage.getItem(SIDEBAR_KEY);
            if (raw) {
                const n = Number(JSON.parse(raw));
                if (!Number.isNaN(n)) return Math.min(SIDEBAR_MAX, Math.max(SIDEBAR_MIN, n));
            }
        } catch { }
        return SIDEBAR_DEFAULT;
    });
    useEffect(() => {
        try { localStorage.setItem(SIDEBAR_KEY, JSON.stringify(sidebarWidth)); } catch { }
    }, [sidebarWidth]);

    const handleSidebarResize = (e) => {
        e.stopPropagation();
        e.preventDefault();
        const startX = e.pageX;
        const startW = sidebarWidth;
        const onMove = (mv) => {
            const next = Math.min(SIDEBAR_MAX, Math.max(SIDEBAR_MIN, startW + (mv.pageX - startX)));
            setSidebarWidth(next);
        };
        const onUp = () => {
            window.removeEventListener('pointermove', onMove);
            window.removeEventListener('pointerup', onUp);
            document.body.style.cursor = 'default';
            document.body.style.userSelect = '';
        };
        window.addEventListener('pointermove', onMove);
        window.addEventListener('pointerup', onUp);
        document.body.style.cursor = 'col-resize';
        document.body.style.userSelect = 'none';
    };

    // ---------- Wheel -> horizontal scroll on the columns container ----------
    const columnsScrollerRef = useRef(null);
    useEffect(() => {
        const el = columnsScrollerRef.current;
        if (!el) return;
        const onWheel = (e) => {
            // If a child (e.g. the chart) has already handled it, skip
            if (e.defaultPrevented) return;
            // Convert vertical wheel into horizontal scroll
            if (e.deltaY !== 0 || e.deltaX !== 0) {
                e.preventDefault();
                el.scrollLeft += (e.deltaY || 0) + (e.deltaX || 0);
            }
        };
        el.addEventListener('wheel', onWheel, { passive: false });
        return () => el.removeEventListener('wheel', onWheel);
    }, []);

    // Make sure when STOCK_LIST grows (user adds an extra stock) we have an
    // empty bucket ready for the new id.
    useEffect(() => {
        setHistories(prev => {
            const next = { ...prev };
            let changed = false;
            for (const s of STOCK_LIST) {
                if (!(s.id in next)) {
                    next[s.id] = [];
                    changed = true;
                }
            }
            return changed ? next : prev;
        });
        setSnapshots(prev => {
            const next = { ...prev };
            let changed = false;
            for (const s of STOCK_LIST) {
                if (!(s.id in next)) {
                    next[s.id] = { ltp: null, vol: null };
                    changed = true;
                }
            }
            return changed ? next : prev;
        });
    }, [STOCK_LIST]);

    // depthData mirror so the sampling effect doesn't reset every 50ms
    // depthData (the throttled state from useMarketData) is no longer used by
    // the bucketing path — we drive everything off WS packet events instead so
    // the data stays accurate even when this tab is in the background. The
    // sidebar / footer Cum Vol still read from `snapshots`, which is now
    // updated via processPacket → render-sync interval below.

    // Mirror STOCK_LIST into a ref so the sampling interval can read the
    // latest list without being torn down on every re-render.
    const stockListRef = useRef(STOCK_LIST);
    useEffect(() => { stockListRef.current = STOCK_LIST; }, [STOCK_LIST]);

    // Mirror bucketSize so the sampling interval picks up the new value
    // without being torn down.
    // Note: there used to be a bucketRef here that processPacket read to
    // decide its bucketing. processPacket now ALWAYS uses 15-second buckets
    // (raw source of truth) so the ref is no longer needed.

    // Mirror WS status so sampling can skip while disconnected.
    const wsStatusRef = useRef(wsStatus);
    useEffect(() => { wsStatusRef.current = wsStatus; }, [wsStatus]);

    // Mirror marketOpen so processPacket can skip cleanly during non-trading
    // hours without the user having to unplug anything.
    const marketOpenRef = useRef(marketOpen);
    useEffect(() => { marketOpenRef.current = marketOpen; }, [marketOpen]);

    // NOTE: there used to be a bucket-change wipe / re-aggregate effect here.
    // It's been removed because the source-of-truth `histories` state now
    // ALWAYS holds raw 1-minute buckets, and the displayed view is derived
    // via `displayedHistories = useMemo(...)` further down. Switching the
    // timeframe just causes that memo to recompute — the raw data stays
    // intact, so going 1m → 5m → 1m correctly returns to the original detail.

    // Live timer tick
    useEffect(() => {
        const id = setInterval(() => setTimeTick(t => t + 1), 1000);
        return () => clearInterval(id);
    }, []);

    // Persist state to localStorage every 2s + on unload
    const histRef = useRef(histories);
    const snapRef = useRef(snapshots);
    useEffect(() => { histRef.current = histories; }, [histories]);
    useEffect(() => { snapRef.current = snapshots; }, [snapshots]);

    useEffect(() => {
        const flush = () => {
            try {
                // Persisted data is always RAW 15s (the source of truth).
                // The bucketSize tag is fixed at RAW_BUCKET_MINUTES so the loader knows.
                localStorage.setItem(STORAGE_KEY, JSON.stringify({
                    day: todayKey(),
                    bucketSize: RAW_BUCKET_MINUTES,
                    histories: histRef.current,
                    snapshots: snapRef.current,
                }));
            } catch { }
        };
        const id = setInterval(flush, 2000);
        window.addEventListener('beforeunload', flush);
        return () => {
            clearInterval(id);
            window.removeEventListener('beforeunload', flush);
            flush();
        };
    }, []);

    // Subscribe whenever the stock list changes
    useEffect(() => {
        if (typeof subscribe !== 'function') return;
        const quotes = STOCK_LIST.map(s => ({
            Xchg: s.xchg,
            Tkn: s.tkn,
            Symbol: s.symbol,
        }));
        try {
            subscribe(quotes, 1);
        } catch (e) {
            console.warn('[VerticalLayout] subscribe failed', e);
        }
    }, [subscribe, STOCK_LIST]);

    // ===========================================================
    // ====   EVENT-DRIVEN PACKET PROCESSING (background-safe)  ===
    // ===========================================================
    //
    // Every WebSocket data packet (Touchline / MarketData / IndexData / Depth)
    // fires a 'depth-packet' event on `depthEvents`. We process each packet
    // SYNCHRONOUSLY into mutable refs (`historiesRef` / `snapshotsRef`).
    // No setInterval is involved in the bucketing path, so the data stays
    // accurate even when the tab is backgrounded and timers get throttled.
    //
    // A separate 1 Hz "render sync" interval copies the refs into React state
    // so the UI re-renders. That interval IS still timer-throttled in the
    // background, but it only affects how often the UI updates — the
    // underlying numbers are always correct.

    // Mutable per-stock state. These are the source of truth for bucketing.
    const historiesRef = useRef(histories);
    const snapshotsRef = useRef(snapshots);
    // Keep refs in sync with state when state changes from outside (clear,
    // remove, persistence load, etc).
    useEffect(() => { historiesRef.current = histories; }, [histories]);
    useEffect(() => { snapshotsRef.current = snapshots; }, [snapshots]);

    // The packet processor — runs synchronously inside the WS message handler.
    // All inputs (stock list, bucket size, ws status) are read from refs so
    // this function never goes stale.
    const processPacket = (packet) => {
        if (!packet) return;
        if (wsStatusRef.current !== 'connected') return;
        // Freeze state outside market hours — no new rows, no bucket updates.
        if (!marketOpenRef.current) return;

        const tkn = packet.Tkn || packet.Token;
        if (!tkn) return;
        const tknStr = String(tkn);
        const stock = stockListRef.current.find(s => String(s.tkn) === tknStr);
        if (!stock) return;

        const vol = readField(packet, VOLUME_KEYS);
        const ltp = readField(packet, PRICE_KEYS);
        if (vol === null && ltp === null) return;

        const now = packet._receivedAt || Date.now();
        // ALWAYS bucket the source-of-truth at raw 15-second granularity. The
        // displayed view aggregates this on demand via the displayedHistories
        // useMemo, so changing the timeframe is non-destructive — going
        // 15s → 1m → 5m → 15s returns to the original detail.
        const minuteKey = fmtBucket(now, RAW_BUCKET_MINUTES);

        // ----- snapshots -----
        const curSnap = snapshotsRef.current[stock.id] || { ltp: null, vol: null };
        if ((vol !== null && vol !== curSnap.vol) || (ltp !== null && ltp !== curSnap.ltp)) {
            snapshotsRef.current = {
                ...snapshotsRef.current,
                [stock.id]: {
                    ltp: ltp !== null ? ltp : curSnap.ltp,
                    vol: vol !== null ? vol : curSnap.vol,
                },
            };
            snapshotsDirtyRef.current = true;
        }

        // ----- histories -----
        if (vol === null) return; // need vol for history bucket math

        const arr = historiesRef.current[stock.id] || [];
        const last = arr[arr.length - 1];

        if (!last || last.minute !== minuteKey) {
            // Cross-boundary flush — see explanation in old code: any volume
            // that crossed the minute boundary belongs to the previous bucket.
            let workingArr = arr;
            if (
                last &&
                vol > last.cumVol &&
                (now - (last.timestamp || 0)) < Math.round(RAW_BUCKET_MINUTES * 60 * 1.5) * 1000
            ) {
                const lastStartCum = last.startCum ?? last.cumVol - last.delta;
                workingArr = [...arr.slice(0, -1), {
                    ...last,
                    cumVol: vol,
                    delta: Math.max(0, vol - lastStartCum),
                    priceClose: ltp ?? last.priceClose,
                }];
            }

            const newRow = {
                minute: minuteKey,
                cumVol: vol,
                delta: 0,
                timestamp: now,
                startCum: vol,
                priceOpen: ltp,
                priceClose: ltp,
            };
            let newArr = [...workingArr, newRow];
            if (newArr.length > 1500) newArr = newArr.slice(-1500);
            historiesRef.current = { ...historiesRef.current, [stock.id]: newArr };
            historiesDirtyRef.current = true;
        } else if (vol !== last.cumVol || (ltp !== null && ltp !== last.priceClose)) {
            const startCum = last.startCum ?? last.cumVol - last.delta;
            const updated = {
                ...last,
                cumVol: vol,
                delta: Math.max(0, vol - startCum),
                timestamp: now,
                startCum,
                priceOpen: last.priceOpen ?? ltp,
                priceClose: ltp ?? last.priceClose,
            };
            historiesRef.current = {
                ...historiesRef.current,
                [stock.id]: [...arr.slice(0, -1), updated],
            };
            historiesDirtyRef.current = true;
        }
    };

    // Dirty flags so the render-sync interval only re-renders when something
    // actually changed. Avoids waste between ticks.
    const historiesDirtyRef = useRef(false);
    const snapshotsDirtyRef = useRef(false);

    // ----- Subscribe to the packet event bus -----
    useEffect(() => {
        if (!depthEvents) return;
        const handler = (e) => processPacket(e.detail);
        depthEvents.addEventListener('depth-packet', handler);
        return () => depthEvents.removeEventListener('depth-packet', handler);
    // processPacket is stable (closes over refs only), so we don't list it
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [depthEvents]);

    // ----- 1 Hz render sync — copy refs to React state for re-render -----
    // Throttled when tab is in background, but that's fine: the underlying
    // refs are always correct, the UI just updates less often when hidden.
    useEffect(() => {
        const flushToState = () => {
            if (historiesDirtyRef.current) {
                setHistories(historiesRef.current);
                historiesDirtyRef.current = false;
            }
            if (snapshotsDirtyRef.current) {
                setSnapshots(snapshotsRef.current);
                snapshotsDirtyRef.current = false;
            }
        };
        const id = setInterval(flushToState, 1000);

        // When the tab returns to foreground, flush immediately so the UI
        // catches up with everything that the event handler accumulated while
        // we were hidden.
        const onVisible = () => {
            if (document.visibilityState === 'visible') flushToState();
        };
        document.addEventListener('visibilitychange', onVisible);

        return () => {
            clearInterval(id);
            document.removeEventListener('visibilitychange', onVisible);
            flushToState();
        };
    }, []);

    const handleClear = (stockId) => {
        setHistories(prev => ({ ...prev, [stockId]: [] }));
    };

    const handleClearAll = () => {
        setHistories(Object.fromEntries(STOCK_LIST.map(s => [s.id, []])));
        try { localStorage.removeItem(STORAGE_KEY); } catch { }
    };

    const handleRemoveStock = (stockId) => {
        if (typeof onRemoveExtraStock === 'function') onRemoveExtraStock(stockId);
        setHistories(prev => {
            const next = { ...prev };
            delete next[stockId];
            return next;
        });
        setSnapshots(prev => {
            const next = { ...prev };
            delete next[stockId];
            return next;
        });
    };

    // Listen for the global "Clear" button in App.jsx top bar. The event
    // carries detail.monitorId so only the targeted monitor clears.
    useEffect(() => {
        const onClearAll = (e) => {
            const targetId = e?.detail?.monitorId;
            if (targetId != null && targetId !== monitorId) return;
            handleClearAll();
        };
        window.addEventListener('vl-clear', onClearAll);
        return () => window.removeEventListener('vl-clear', onClearAll);
    }, [STOCK_LIST, monitorId]);

    return (
        <VolumeUnitContext.Provider value={volumeUnit}>
            <div className="flex h-full overflow-hidden bg-[#050505]">
                {/* Slim resizable left sidebar */}
                <div className="relative h-full flex-shrink-0" style={{ width: sidebarWidth }}>
                    <LeftSidebar
                        stocks={orderedStocks}
                        histories={displayedHistories}
                        snapshots={snapshots}
                        width={sidebarWidth}
                    />
                    {/* Sidebar right-edge resize handle */}
                    <div
                        className="absolute right-0 top-0 w-1.5 h-full cursor-col-resize hover:bg-blue-500/30 z-50 transition-colors"
                        onPointerDown={handleSidebarResize}
                        title="Drag to resize sidebar"
                    />
                </div>

                {/* Main columns area — wheel scrolls horizontally */}
                <div
                    ref={columnsScrollerRef}
                    className="flex-1 overflow-x-auto overflow-y-hidden p-2 relative"
                >
                    <div className="flex h-full gap-4 pb-4 w-fit min-w-full items-stretch">
                        <Reorder.Group
                            axis="x"
                            values={columnOrder}
                            onReorder={setColumnOrder}
                            className="flex h-full gap-4 list-none"
                        >
                            {orderedStocks.map(stock => (
                                <StockColumn
                                    key={stock.id}
                                    stock={stock}
                                    isExtra={!!stock.isExtra}
                                    history={displayedHistories[stock.id] || []}
                                    ltp={snapshots[stock.id]?.ltp ?? null}
                                    cumVolume={snapshots[stock.id]?.vol ?? 0}
                                    width={columnWidths[stock.id] ?? COL_DEFAULT_W}
                                    onResize={handleResize}
                                    onClear={handleClear}
                                    onRemove={handleRemoveStock}
                                    bucketSize={bucketSize}
                                    intVolMinutes={intVolMinutes[stock.id] ?? 5}
                                    onChangeIntVol={handleChangeIntVol}
                                    consensusByMinute={consensusByMinute}
                                />
                            ))}
                        </Reorder.Group>

                        {/* Pinned aggregate columns at the end — NOT part of
                            the Reorder.Group, so they can't be dragged away. */}
                        <TotalsColumn
                            stocks={orderedStocks}
                            histories={displayedHistories}
                        />
                        <NetColumn
                            stocks={orderedStocks}
                            histories={displayedHistories}
                        />
                    </div>
                </div>
            </div>
        </VolumeUnitContext.Provider>
    );
};

export default VerticalLayout;
